### ISSUE TITLE
Sum quantitative values in hexbin

### ISSUE THREAD

**Issue by dbabbs** [heremaps/here-cli#106]
My data has a quantitative value `count`. I would like the output of my hexbin binning sum up a particular property value. This way, I can access the aggregated value in the hexbin's properties.

**Comment by burritojustice** [comment]
this is a great idea -- maybe `-a/--aggregate`

    here xyz hexbin spaceID -a property_name -z...

cc @Naitik333

**Comment by burritojustice** [comment]
This would be a sum of all the values of the chosen property in that hexbin. 

Say the points represented property values, and you wanted to add up all of the up property values in that bin, there would be a new `sum`property. There'd also be a `maxSum` for the highest value seen in any hexbin, in addition to maxCount. And if we're adding them up, we could do mean and median values for that cell. 

I think it would act a lot like the subcounts we do -- you'd have a property name, and then the sum data.

**Comment by burritojustice** [comment]
looking good!

**Comment by dbabbs** [comment]
When will this be merged?

**Comment by burritojustice** [comment]
When we finish the open source review for 1.0.2. 

In the meantime, you can build master locally and run it via

    node here.js xyz hexbin spaceID -a propertyToAdd
