### ISSUE TITLE
Password Secrets are shown as plain text in 'here configure set'

### ISSUE THREAD

**Issue by cpandit201** [heremaps/here-cli#117]
Password secrets are shown as plain text in here configure set command

![image](xhttps://user-images.githubusercontent.com/42322819/63403427-d5f09700-c3fc-11e9-8a48-443ef0313b9e.png)

**Comment by burritojustice** [comment]
@cpandit201 Can you let us know what version of the HERE CLI you are running (`here -V`), along with your OS and version of node?

**Comment by cpandit201** [comment]
I was using v1.0.1 on windows with Git Bash (https://git-scm.com/download/win) to simulate Command Line Terminal on windows using MINGW64

**Comment by cpandit201** [comment]
Yes thanks for pointing that out, Found out it is a known issue of Git-bash. Closing this issue from our end.

Quoting below from the article https://www.bountysource.com/issues/48239126-git-bash-doesn-t-mask-hide-passwords

> 
> The thing to understand first is that MinTTY does not implement a Win32 Console. Instead, it uses MSYS2's pty emulation. Therefore vagrant is absolutely correct in saying that it cannot hide the password: it really cannot, unless it learns about MSYS2's pty emulation. Which would of course be asking a bit much... what other terminal emulators should vagrant support in addition to MinTTY?
> 
> That is why you have winpty. It does offer a Win32 Console to the spawned process. And then polls that to update MinTTY's pty accordingly. Obviously, this is somewhat slow, and even error-prone. That's why it is not the default.
> 
> If you want a TL;DR, I first have to tell you: it is a mistake to not read what I wrote above, because it is a rather crucial bit of information. The answer to your question is obviously: no, there is no known way to fix this issue, and therefore it likely won't be fixed. https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues
