### ISSUE TITLE
detect and convert CRS of shapefiles if not wgs84

### ISSUE THREAD

**Issue by burritojustice** [heremaps/here-cli#12]
`shapefiles` often have coordinates in feet or meters based off a local coordinate reference system (CRS) stored in the `.prj` file. We should be able to detect these, and re-project to wgs84 as we convert to geojson.

Here's a sample file of San Francisco voting precincts where the CRS is `NAD_1983_StatePlane_California_III_FIPS_0403_Feet` 

https://sfelections.sfgov.org/sites/default/files/Documents/Maps/2017lines.zip

The `x,y` coordinates look like `[5998951.291892946,2113203.1748289317]` which causes the XYZ Hub API to respond with `Command Failure :"{\"type\":\"ErrorResponse\",\"streamId\":\"e34dc5cd-dc71-11e8-9f8e-675838c2c7e5\",\"error\":\"IllegalArgument\",\"errorMessage\":\"The longitude (1rst) value in coordinates of the Point is out of bounds (< -180 or > +180).` (more detail below)

This is easy to convert to WGS84 and GeoJJSON using in QGIS or gdal or mapshaper

`mapshaper SF_DOE_Precincts_2017.shp -proj wgs84 -o format=geojson sf_precincts.geojson`

https://github.com/mbloch/mapshaper/wiki/Command-Reference#-proj

`ogr2ogr -f GeoJSON -t_srs crs:84 sf_precincts.geojson SF_DOE_Precincts_2017.shp`

https://www.gdal.org/drv_geojson.html

It would be good to have our CLI shapefile converter also handle this.

extended error message:

```Command Failure :"{\"type\":\"ErrorResponse\",\"streamId\":\"e34dc5cd-dc71-11e8-9f8e-675838c2c7e5\",\"error\":\"IllegalArgument\",\"errorMessage\":\"The longitude (1rst) value in coordinates of the Point is out of bounds (< -180 or > +180). Feature: \\n{\\n\\t\\\"type\\\": \\\"Feature\\\",\\n\\t\\\"properties\\\": {\\n\\t\\t\\\"SupDist\\\": \\\"1\\\",\\n\\t\\t\\\"Shape_Leng\\\": 8028.23412216,\\n\\t\\t\\\"BARTDist\\\": \\\"8\\\",\\n\\t\\t\\\"AssemDist\\\": \\\"19\\\",\\n\\t\\t\\\"CongDist\\\": \\\"12\\\",\\n\\t\\t\\\"NeighRep\\\": \\\"LRL HTS/ANZA\\\",\\n\\t\\t\\\"PREC_2012\\\": \\\"9151\\\",\\n\\t\\t\\\"PREC_2010\\\": \\\"2134\\\",\\n\\t\\t\\\"Shape_Le_1\\\": 8028.23412216,\\n\\t\\t\\\"Shape_Area\\\": 2587344.30036,\\n\\t\\t\\\"PREC_2017\\\": \\\"9151\\\",\\n\\t\\t\\\"@ns:com:here:xyz\\\": {\\n\\t\\t\\t\\\"tags\\\": [\\n\\t\\t\\t\\t\\\"precincts\\\",\\n\\t\\t\\t\\t\\\"SF_DOE_Precincts_2017\\\"\\n\\t\\t\\t],\\n\\t\\t\\t\\\"space\\\": \\\"13nrAXcV\\\"\\n\\t\\t}\\n\\t},\\n\\t\\\"geometry\\\": {\\n\\t\\t\\\"type\\\": \\\"Polygon\\\",\\n\\t\\t\\\"coordinates\\\": [\\n\\t\\t\\t[\\n\\t\\t\\t\\t[\\n\\t\\t\\t\\t\\t5998951.291892946,\\n\\t\\t\\t\\t\\t2113203.1748289317\\n\\t\\t\\t\\t],\\n\\t\\t\\t\\t[\\n\\t\\t\\t\\t\\t5998947.108174279,\\n\\t\\t\\t\\t\\t2113127.144141108\\n\\t\\t\\t\\t],\\n\\t\\t\\t\\t[\\n\\t\\t\\t\\t\\t5998888.217544019,\\n\\t\\t\\t\\t\\t2112950.2757284343\\n\\t\\t\\t\\t],\\n\\t\\t\\t\\t[\\n\\t\\t\\t\\t\\t5998876.132594436,\\n\\t\\t\\t\\t\\t2112883.5143790245\\n\\t\\t\\t\\t],\\n\\t\\t\\t\\t[\\n\\t\\t\\t\\t\\t5998894.284132943,\\n\\t\\t\\t\\t\\t2112755.666209519\\n\\t\\t\\t\\t],\\n\\t\\t\\t\\t[\\n\\t\\t\\t\\t\\t5998878.866512865,\\n\\t\\t\\t\\t\\t2112723.2092534304\\n\\t\\t\\t\\t],\\n\\t\\t\\t\\t[\\n\\t\\t\\t\\t\\t5998899.519358695,\\n\\t\\t\\t\\t\\t2112701.655490771\\n\\t\\t\\t\\t],\\n\\t\\t\\t\\t[\\n\\t\\t\\t\\t\\t5998928.928420603,\\n\\t\\t\\t\\t\\t2112420.2449643463\\n\\t\\t\\t\\t],\\n\\t\\t\\t\\t[\\n\\t\\t\\t\\t\\t5998919.87463294,\\n\\t\\t\\t\\t\\t2112388.019635096\\n\\t\\t\\t\\t],\\n\\t\\t\\t\\t[\\n\\t\\t\\t\\t\\t5998937.395923361,\\n\\t\\t\\t\\t\\t2112354.8769848496\\n\\t\\t\\t\\t],\\n\\t\\t\\t\\t[\\n\\t\\t\\t\\t\\t5999005.86757119,\\n\\t\\t\\t\\t\\t2111866.8805855215\\n\\t\\t\\t\\t],\\n\\t\\t\\t\\t[\\n\\t\\t\\t\\t\\t5998998.4338590205,\\n\\t\\t\\t\\t\\t2111829.158220023```

**Comment by dhaneeshtnair** [comment]
We will be providing this capability post GA release

**Comment by burritojustice** [comment]
This has been working well with everything I've tested.

**Comment by burritojustice** [comment]
getting an error with this shapefile:

https://opendata-ajuntament.barcelona.cat/data/en/dataset/terrasses-comercos-vigents

prj:

```PROJCS["ETRS89_UTM_zone_31N",GEOGCS["GCS_ETRS_1989",DATUM["D_ETRS_1989",SPHEROID["GRS_1980",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",3],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["Meter",1]]```

**Comment by burritojustice** [comment]
looks like something broke in the CRS detection code -- shapefiles with non-WGS84 PRJs that were successfully uploading with the new code are now failing 

[hinan01_01 (1).zip](https://github.com/heremaps/here-cli/files/3503087/hinan01_01.1.zip)

**Comment by burritojustice** [comment]
disregard, I was on 1.0.1, not master :)
