### ISSUE TITLE
echo space ID after upload has finished when streaming

### ISSUE THREAD

**Issue by burritojustice** [heremaps/here-cli#123]
After an upload or hexbin creation, we should echo the space ID so users don't have to scroll all the way back.

See also 
https://github.com/heremaps/here-cli/issues/101 
and especially
https://github.com/heremaps/here-cli/issues/102

**Comment by burritojustice** [comment]
it would be nice to say "123,456 features uploaded to XYZ space A1b2C3d4 in 2 minutes"

at minimum, we should echo `here xyz config` and `here xyz config --stats`

**Comment by Naitik333** [comment]
fixed and released in version 1.2.0
