### ISSUE TITLE
here xyz upload shape file won't finish uploading

### ISSUE THREAD

**Issue by nzjony** [heremaps/here-cli#133]
1. here xyz create
1. here xyz upload <space_id> -f vegetacao_5000.shp

Takes a long time to upload > 10 mins and counting

Dataset is here: https://drive.google.com/drive/folders/1MgsIQdIyBo6n6vrm9uudNj7SnXXDo_Cc

**Comment by nzjony** [comment]
Using mapshaper to convert to geojson and uploading it works fine, see: https://xyz.here.com/viewer/?project_id=b6eb5508-6ebf-4394-a036-2f167c9fba34

**Comment by burritojustice** [comment]
Hey @nzjony, thanks for letting us know, I'm having the same issues. We're looking into it.

What's the source of the shapefile?

**Comment by nzjony** [comment]
hey @burritojustice, it was a data set that is available from giscloud.com, it is one of their custom examples, I wanted to do some performance testing in harp.gl using data in an xyz space and compare to their offering, so I don't claim to understand if it is a valid shape file or not.

**Comment by burritojustice** [comment]
@nzjony that shapefile had some null characters in it, which threw us into an infinite loop. We now check for that. It's in a branch and will get merged to master soon.

```{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"mslink":1690,"mapid":6000137,"cod_leg_ca":"00Magua","cod_class_":"00Magua","dsc_class_":"Massa Dagua Continental","dsc_veg_pr":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","val_area_k":533.7361,"val_perime":766.8376,"id1":1,```
