### ISSUE TITLE
import gpx files

### ISSUE THREAD

**Issue by burritojustice** [heremaps/here-cli#139]
GPX is a popular format for recording running and biking data.

A well thought out library for converting GPX to GeoJSON (made by the Studio team) is here.

https://github.com/roberto-butti/fit-geojson-vuejs

The resulting output would look like this:

https://xyz-space-invader.netlify.com/?space=m5pmsnx1&token=AFbjoHrBlTB2K5_gqvcP_S8&basemap=xyz-pixel-dark&buildings=0&label=&colors=range&points=0&lines=0&outlines=0&highlight=0&places=0&roads=1&water=0&property=ele&palette=temperature&paletteFlip=true&rangeFilter=4&sort=values&hideOutliers=false#12.719989900291463/37.7560/-122.4353

![image](https://user-images.githubusercontent.com/3979711/64496050-9b915180-d266-11e9-8b55-461916f7ae26.png)

**Comment by roberto-butti** [comment]
<img width="733" alt="Screenshot 2019-12-09 at 22 36 36" src="https://user-images.githubusercontent.com/678434/70475280-87165c80-1ad4-11ea-9f83-f242872c80bc.png">
Work in progress :rocket:

**Comment by burritojustice** [comment]
Grazie, @roberto-butti !

**Comment by burritojustice** [comment]
I'd suggest that you use the syntax

`here xyz upload -f my.gpx` and use the extension detection we use for .`csv` and `.geojson`

and add the `gpx2geo` logic to `transform.ts`

https://github.com/heremaps/here-cli/blob/master/src/here-xyz.ts#L1375

https://github.com/heremaps/here-cli/blob/master/src/here-transform.ts#L33

Let me know if you have any questions!

cc @Naitik333

**Comment by roberto-butti** [comment]
Thank you for the suggestion @burritojustice . In my "spare time", at the moment I'm focused on _trasform_ just to understand the logic under the hood and how is structured the code.
Once I will have a consolidated geojson from transform I can shift my focus on _detection_ and _upload_.

**Comment by roberto-butti** [comment]
"Here" the Pull Request: https://github.com/heremaps/here-cli/pull/179 #179

**Comment by burritojustice** [comment]
this is looking good in the latest build!
