### ISSUE TITLE
fix hexbin bbox (negative longitudes)

### ISSUE THREAD

**Issue by burritojustice** [heremaps/here-cli#142]
`here xyz hexbin --bbox` takes a `minLon,maxLon,minLat,maxLat` argument. If the minLon is negative (e.g. the western hemisphere), the CLI interprets the `-` as a argument.

Adding quotes doesn't help.

You can get it to work with some bash escape fu (note the space):

`here xyz hexbin spaceID --bbox \ -123.0137,37.6040,-122.3549,37.83`

but this is... not ideal.

**Comment by Naitik333** [comment]
user can use \ for giving negative values - 
here xyz hexbin spaceID --bbox \ -123.0137,37.6040,-122.3549,37.83

alternatively user can only specify --bbox and it will ask interactively for bounding box coordinates.
Fixed in release 1.2.0.
