### ISSUE TITLE
Uploading this Geojson throws an unhandled exception

### ISSUE THREAD

**Issue by deadnight7** [heremaps/here-cli#143]
Uploading below GeoJSON File goes into an exception 
Stations GeoJSON CSV File - https://gist.github.com/deadnight7/def232e0f11e551e97f72d966e66a057

> ### 
> 
> 3inmcpandit1:Downloads cpandit$ here xyz upload -f stations3_COLOR_PROPERTY.csv
> You have not supplied any space id, creating a new xyz space for this upload..
> ? Enter a title for the new space :  
> ? Enter a description for the new space :  stations3_COLOR_PROPERTY.csv
> 
> xyzspace 'JxIc4E5a' created successfully
> (node:24366) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'tags' on string 'all_month_earthquakes_data|VFetk7B0|1566907876753|1566910149111'
>     at /usr/local/lib/node_modules/@here/cli/bin/here-xyz.js:1444:28
>     at Array.forEach (<anonymous>)
>     at /usr/local/lib/node_modules/@here/cli/bin/here-xyz.js:1381:18
>     at Generator.next (<anonymous>)
>     at /usr/local/lib/node_modules/@here/cli/bin/here-xyz.js:8:71
>     at new Promise (<anonymous>)
>     at __awaiter (/usr/local/lib/node_modules/@here/cli/bin/here-xyz.js:4:12)
>     at mergeAllTags (/usr/local/lib/node_modules/@here/cli/bin/here-xyz.js:1371:12)
>     at /usr/local/lib/node_modules/@here/cli/bin/here-xyz.js:1304:46
>     at Generator.next (<anonymous>)
> (node:24366) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:24366) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by burritojustice** [comment]
Hi @deadnight7, this looks like a GeoJSON file with nested properties that got converted into a flat CSV.  The last column is what was the `@ns` object. Normally XYZ will read that and apply tags, but is failing because it is no longer parseable as plain text.

You can either a) download the data as actual GeoJSON, or b) delete that last "@ns:com:here:xyz" column.

How did it get exported as CSV from XYZ? Can you explain the process?
