### ISSUE TITLE
import of shapefiles from StatsCan fails

### ISSUE THREAD

**Issue by burritojustice** [heremaps/here-cli#148]
The CLI is not able to convert this shapefile with a PCS Lambert Conformal Conic projections.

https://www12.statcan.gc.ca/census-recensement/2011/geo/bound-limit/bound-limit-2016-eng.cfm

[lcma000b16a_e.zip](https://github.com/heremaps/here-cli/files/3649126/lcma000b16a_e.zip)

coordinates > 180, < -180 etc

`mapshaper` can convert it:

`mapshaper lcsd000b16a_e.shp encoding=utf8 -simplify 5% -proj wgs84 -o format=geojson - | here xyz upload [SPACEID] -t 2016_municipalities -c 1 -s -i CSDUID`

**Comment by Naitik333** [comment]
I tried uploading the shape file in 1.2.0 and it uploaded successfully.

```
(base) 3inmnisar1:here-cli nisar$ here xyz upload dIGrABU9 -f ~/Downloads/lcma000b16a_e/lcma000b16a_e.shp -c 10
/Users/nisar/Downloads/lcma000b16a_e/lcma000b16a_e.prj file exists, using this file for crs transformation
uploaded 100.00%
data upload to xyzspace 'dIGrABU9' completed
```
