### ISSUE TITLE
upload -s (streaming) is getting stuck

### ISSUE THREAD

**Issue by burritojustice** [heremaps/here-cli#154]
seeing cases where streaming CSVs is getting stuck, usually at the very end of the file.

These file gets to the end, but it doesn't give the prompt back.

[csv_streaming.zip](https://github.com/heremaps/here-cli/files/3659381/csv_streaming.zip)

these files are getting stuck halfway through, but I think it's because they are asking for the lat/lon too many times (it's null, so it should always just tag it and move along, no need to prompt the user)

[bike_streaming_stuck.zip](https://github.com/heremaps/here-cli/files/3659396/bike_streaming_stuck.zip)

**Comment by Naitik333** [comment]
Fixed in version 1.0.2
