### ISSUE TITLE
Copy space ID to clipboard after creating space

### ISSUE THREAD

**Issue by dbabbs** [heremaps/here-cli#158]
**Background**
Current workflow for creating space and uploading data: 
1. Run `here xyz create -t "sample space" -d "a description"
2. Manually select and copy space ID from step 1's response.
3. Run `here xyz upload ...` while pasting space ID

**Proposal**
After step 1, automatically copy space id to the keyboard. This way, step 2 is eliminated and step 3 can be executed even more quickly

**Comment by burritojustice** [comment]
Good idea on the clipboard. We have been looking at a few ways to make that easier.

In the meantime, you no longer need to specify a spaceID with `upload -f`! It will make one for you automatically.
