### ISSUE TITLE
wgs84 shapefile upload causes connector error 

### ISSUE THREAD

**Issue by burritojustice** [heremaps/here-cli#165]
Uploading this WGS84 shapefile fails with a connector error (using the current version in master):

[SFMTA Bikeway Network.zip](https://github.com/heremaps/here-cli/files/3799999/SFMTA.Bikeway.Network.zip)

```
$ node bin/here.js xyz upload 3Z1TdhZ5 -f /Users/joram/Documents/Documents\ -\ 1usmjoram/HERE/training/SFMTA\ Bikeway\ Network/geo_export_006b1dac-cd06-48c0-9e53-6c28fe6f6e90.shp -c 10
/Users/joram/Documents/Documents - 1usmjoram/HERE/training/SFMTA Bikeway Network/geo_export_006b1dac-cd06-48c0-9e53-6c28fe6f6e90.prj file exists, using this file for crs transformation
OPERATION FAILED : {"type":"ErrorResponse","error":"BadGateway","errorMessage":"Connector error.","streamId":"13183b04-9a1d-45c2-8c59-c02e931ab6f2"}
```
Adjusting chunk size has no effect.

I can convert this using `mapshaper` and upload.

Note that this version uploads without issue in 1.0.1

**Comment by Naitik333** [comment]
It was not working earlier as well, it was not showing proper error messages earlier which was fixed later on after 1.0.1
