### ISSUE TITLE
show feature count in clear and delete "are you sure" prompt

### ISSUE THREAD

**Issue by burritojustice** [heremaps/here-cli#173]
When users issue a `clear` or `delete` command, we prompt them with an "are you sure?" warning.

We should also report the number of features that would be affected using the /statistics endpoint, and the type (number of points, lines, or features)

Also, title and description.

If the user is using `clear -t tagname`, we should display the count for that tag via statistics.

**Comment by viralsejpalhere** [comment]
Hello, This is indeed a good suggestion. This is part of the release 1.2.0.
