### ISSUE TITLE
Environment variables issue with v1.5.0 on Windows 10

### ISSUE THREAD

**Issue by FelixVanOost** [heremaps/here-cli#255]
The addition of the line `NODE_OPTIONS=--no-warnings` in `here.ts` as part of commit `aeeb735` appears to cause an issue with environment variables on Windows 10 installations. Running the `here` command on v1.5.0 of the CLI now returns the following result:

```
'NODE_OPTIONS' is not recognized as an internal or external command, operable program or batch file.
```

I have currently been unable to find a workaround for this that doesn't involve removing the line and re-compiling the package. Is this something that could be looked at for the next release?

**Comment by jaidatts** [comment]
@FelixVanOost , we are looking into this.
Which node version are you running Here CLI on? 
The error seems to point to a PATH issue.

**Comment by FelixVanOost** [comment]
@jaidatts Thanks for quick response! I'm on Node v10.16.3.

**Comment by jaidatts** [comment]
@FelixVanOost , thanks for letting us know the version. We were able to reproduce is on v10.16.3. However it doesn't happen with newer versions of node v10. It might be a feature breakage in that version. Can you try upgrading to the latest v10 node: v10.21.0?

**Comment by FelixVanOost** [comment]
@jaidatts It's working again now after updating to Node v12.18.2 (LTS) and completely reinstalling the CLI. I can't believe I didn't think of updating Node earlier...

Thanks for the quick support and for the work that's being put into this. I'm really enjoying XYZ Studio. 👍
