### ISSUE TITLE
Upload via file URL may be breaking the URL

### ISSUE THREAD

**Issue by cfjedimaster** [heremaps/here-cli#270]
I tried the following:

```
xyz upload -f "https://a.mapillary.com/v3/images?client_id=d2R2UUN1WmlBeU9SOWoxSGpWYk82VzpkMzE0ODNmOWI0Y2FiYTMy&closeto=-92.030647375,30.18557175&radius=5000&per_page=500" lIcgmeOq
```

And I got this error:

```
OPERATION FAILED - Error requesting: "{\"message\":\"\\\"lat\\\" is required\",\"invalid_parameter\":\"closeto\"}"
```

When I take the URL and open it directly in the browser, it works fine. So it likes maybe the CLI is dropping part of the URL?

**Comment by cfjedimaster** [comment]
So escaping helped kinda. I tried this:

```
here xyz upload -f "https://a.mapillary.com/v3/images?client_id=d2R2UUN1WmlBeU9SOWoxSGpWYk82VzpkMzE0ODNmOWI0Y2FiYTMy&amp;closeto=-92.030647375,30.18557175&amp;radius=5000&amp;per_page=500" lIcgmeOq
```

And it worked "more", but still cropped stuff. I should have gotten 500 features, but only got 200 (the API default when `per_page` isn't sent. And I got this at the end:

```
OPERATION FAILED - ENOENT: no such file or directory, open '30.18557175&amp;radius=5000&amp;per_page=500'
```

**Comment by cfjedimaster** [comment]
Confirmed. If I use a bit.ly link, it works fine, so the CLI is breaking the URL.

**Comment by burritojustice** [comment]
things like `-` and `&` and `,` are tricky and need to be escaped.

meanwhile use |

`curl 'https://a.mapillary.com/v3/images?client_id=d2R2UUN1WmlBeU9SOWoxSGpWYk82VzpkMzE0ODNmOWI0Y2FiYTMy&closeto=-92.030647375,30.18557175&radius=5000&per_page=500' | here xyz upload yourSpaceID`

**Comment by cfjedimaster** [comment]
Should be easy to encode before sending, right? Or if not and the user must encode, that's fine, but then the docs can make it clear.

And as I mentioned directly to you, the workaround you gave, does the CLI document you can do that?
