### ISSUE TITLE
Document the ability to pipe in data for upload

### ISSUE THREAD

**Issue by cfjedimaster** [heremaps/here-cli#271]
As mentioned here (https://github.com/heremaps/here-cli/issues/270#issuecomment-683154443), the fact that you can pipe in data directly to `here xyz upload` should be documented. Right now nothing in the output of `here xyz upload -h` implies that this is possible.

**Comment by cpandit201** [comment]
Similarly for download, I never know a command like this existed till the point @Naitik333 had suggested to pipe data and output it to file for downloading the entire space data
```here xyz show <spaceId> --all > output.txt```

**Comment by burritojustice** [comment]
thanks -- we are making this more clear in the inline help.
