### ISSUE TITLE
"Value is not a valid number" error, report on the value

### ISSUE THREAD

**Issue by cfjedimaster** [heremaps/here-cli#272]
I'm using this command, which is wrong somehow:

```
here xyz show 2KfXpLCJ --center 29.76,-95.36 --radius 300 --spatial
```

And the result is:

```
OPERATION FAILED : "Value is not a valid number"
```

Ok, I've done something wrong, but which value isn't a number?

**Comment by cfjedimaster** [comment]
It looks like it was `--center`. I figured it out by randomly adding quotes to stuff. Thing is, even if the error said that center was the issue, I would have been confused. It's definitely a number - adding the quotes doesn't make sense for it to help.

**Comment by cfjedimaster** [comment]
It may be Powershell only. Leaving the quotes off in Ubuntu worked. :\

**Comment by burritojustice** [comment]
`--center` requires `lon,lat`, like GeoJSON, not `lat,lon`. Also, some shells are going to interpret the minus sign in longitude to be an argument -- while it's not required by all shells, quoting the coordinates is going to be the safest approach, much like property search.

**Comment by cfjedimaster** [comment]
Why closed? Can't the CLI return a helpful error instead?

**Comment by burritojustice** [comment]
This is a shell / OS specific issue -- if a shell interprets the `-` as an argument we're not going to be able to catch it, but it can be resolved by using quotes around the `lon,lat` value.

**Comment by cfjedimaster** [comment]
Ok, that's fair. What about tweaking the --help text for --center:

"comma separated lon,lat values to specify the center point for radius search"

to:

"comma separated and quoted lon,lat values to specify the center point for radius search"

**Comment by burritojustice** [comment]
Thanks -- yes, we will be specifically referencing quotes for `--center` in the new release.
