### ISSUE TITLE
authenticationController.authenticate(...).then is not a function

### ISSUE THREAD

**Issue by j12y** [heremaps/here-cli#52]
A recent change has resulted in me seeing this error:
```
$ here xyz list
Failed to login : "authenticationController.authenticate(...).then is not a function"
```

Simply running `here configure account` again and logging in with email / password resolves the issue, but error handling could be improved to make it clear what action to take.

**Comment by burritojustice** [comment]
tracking in #57

**Comment by burritojustice** [comment]
much better error handling in the new version of the CLI!
