### ISSUE TITLE
if no space is specified in `here xyz upload`, create one for the user

### ISSUE THREAD

**Issue by burritojustice** [heremaps/here-cli#54]
Creating a space, copying the ID, and pasting it into the `upload` command is cumbersome and error-prone.

I propose that we allow the creation of a space on the fly with `upload` — if there’s no spaceID specified, we create a new one on the fly. 

```
	> here xyz upload -f berlin_bikelanes.geojson
	
	Creating new space for berlin_bikelanes.geojson: 
	Please enter a title: ____
	Please enter a description: __berlin_bikelanes___
	Uploading...
	Created SpaceID a1z2c3y4...
```

I'd also suggest we prompt the user to add a title and a description (though title ought to be mandatory). We should also pre-populate the description with the filename or the URL.

**Comment by jaidatts** [comment]
Implemented in release 1.0.1.

**Comment by burritojustice** [comment]
If I try to upload this CSV without creating a space, it can't figure out the latitude or longitude. The interface to pick the lat/lon is flattened to a single line and it doesn't accept any input.

If I create the space and then upload the file, this file is fine.

(Note that I saw a similar 'flattening' of the lat/lon input with a semi-colon delimited file -- once I selected `;` as the delimited it uploaded fine.)

```burrito:here-cli 07-23-19 18:27:40 $ node bin/here.js xyz upload -f /Users/joram/Downloads/Envista_Projects_for_Paving.csv 
No space ID specified, creating a new XYZ space for this upload.
? Enter a title for the new space:  sf paving 
? Enter a description for the new space :  /Users/joram/Downloads/Envista_Projects_for_Paving.csv
xyzspace 'WsICWAaG' created successfully
? Select property which should be be used for Latitude (Use arrow keys)
❯ project_id,street_name,limits,cnn,project_name_full,owner,description_full,dpw_project_class,facility_type,project_status,start_date,end_date,duration,facility_indicator,facility_subi
ndicator,group_code,facility_type_description,create_date,modify_date,project_type,project_url,X,Y,latitude,longitude,location : (37.7872489128517, -122.460431901545) ```

**Comment by burritojustice** [comment]
here's the CSV https://data.sfgov.org/api/views/bxqh-5px8/rows.csv?accessType=DOWNLOAD

could it have something to do with the `,` in the `location` column?
