### ISSUE TITLE
import CSVs with coordinates in a (lat,lon) format 

### ISSUE THREAD

**Issue by burritojustice** [heremaps/here-cli#55]
CSVs often store coordinates in one column with `(lat,lon`) or `lat,lon` -- we should allow users to select such a field, and we can process it accordingly.

`here xyz upload SPACEID -f points.csv -p point` would designate `points` as the column where (lat,lon) lived.

|INSTALL_YR | INSTALL_MO | OBJECTID | ADDRESS | LOCATION | STREET | PLACEMENT | RACKS | SPACES | LAT | LON | point |
|--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | 
| 2019 | 2 | 4899 | 2325 Union Street | St. Mary's Episcopal | Union Street | SIDEWALK | 1 | 2 |   |   | (37.79653347912768°, -122.43760157990143°) |
| 2019 | 1 | 4933 | 1218 South Van Ness Ave | SF Tikes Academy | South Van Ness Ave | SIDEWALK | 1 | 2 |   |   | (37.7534660999798°, -122.41671916091612°)|
|2019 | 2 | 4920 | 704 Larkin St | Strand Barber & Beauty | Larkin St | SIDEWALK | 2 | 4 |   |   | (37.784378309486456°, -122.41760083180618°)|
 
data via

https://data.sfgov.org/Transportation/Bicycle-Parking/hn4j-6fx5/data?pane=feed

**Comment by ToonvanStrijp** [comment]
@burritojustice Should `-p` override `-lat -lon`?

**Comment by ToonvanStrijp** [comment]
@burritojustice I also would suggest to name the flag `-po` instead of `-p` since it's already taken `-p, --ptag [ptag]", "property names to be used to add tag`

**Comment by burritojustice** [comment]
@ToonvanStrijp good question -- you usually see either `lat` and `lon` columns, or just a `(lat,lon)` column, but I have seen cases where both exist.

I'm assuming that if `lat` and `lon` columns are there along with a `points` column, you want to try the `lat` and `lon` by default, but have an option to fall back to `points` -- I've seen CSVs where the `lat` and `lon` columns are not fully populated, but `points` are.

**Comment by ToonvanStrijp** [comment]
@burritojustice should be easy to implement this kind of behavior. I'll have it done in a few hours.

**Comment by ToonvanStrijp** [comment]
@burritojustice I've added this behavior to the pull request, now it tries to get the `(lat,lon)` first and if not found it checks for the `lat` and `lon` columns, this way the `lat` and `lon` columns are always overwriting the value if found.

**Comment by burritojustice** [comment]
added in 0.2.4
