### ISSUE TITLE
Better Error handling for missing Space ID in Here XYZ CLI 'upload' and 'show' commands

### ISSUE THREAD

**Issue by bkufo** [heremaps/here-cli#56]
Error handling suggestion: If the user uses a non-existent spaceID, they should get an error that says “Space ID : Provided_Name not found”. When I accidentally typed in the following string instead of putting in a real spaceID, I got a really long error message which seemed like a compilation error. 

Can we provide a “Space ID : Provided_Name not found” message?
**Incorrect command**: here xyz upload SPACE_ID -f ne_10m_airports.geojson -p type

Error: UnhandledPromiseRejectionWarning: Error: Invalid response :404
Can we also remove the other parts of the error? Maybe have note saying 'please run your command with '-v' to get more detailed (verbose) output.

See current full error message below:
----------------------------
(node:7192) UnhandledPromiseRejectionWarning: Error: Invalid response :404
    at C:\Users\kufo\AppData\Roaming\npm\node_modules\@here\cli\bin\here-xyz.js:109:23
    at Generator.next (<anonymous>)
   at fulfilled (C:\Users\kufo\AppData\Roaming\npm\node_modules\@here\cli\bin\here-xyz.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
----------------------------

**Comment by burritojustice** [comment]
thanks Babs -- we're looking at how to best catch errors and provide meaningful feedback to the user so they know what to do next for different commands. We'll add `upload` to that list.

**Comment by burritojustice** [comment]
see #57

**Comment by Naitik333** [comment]
We have updated the error handling in the latest release of CLI and fixed the stack trace issue.
