### ISSUE TITLE
provide error catching / handling, and meaningful error messages

### ISSUE THREAD

**Issue by burritojustice** [heremaps/here-cli#57]
catch errors, and provide meaningful feedback, includling steps to resolve problems:

- `413`: upload too large. use `-c` to define a smaller chunk, or simplify feature with mapshaper or QGIS
- `400`: bad coordinates: try reprojecting in mapshaper or QGIS, and check for lat and lon beyond 90/-90,180/180

**Comment by viralsejpalhere** [comment]
Hello, the mentioned issues ( codes : 413, 400 ) are solved and merged into master, will be part of next release. Other general error handling is already resolved in 1.0.0.. 
cheers..! Thank you

**Comment by jaidatts** [comment]
Implemented generic error handling for release 1.0.1.
